# -*- coding: utf-8 -*-
"""T2 - DiazAlejandro.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J6lYI97eGsgLTxHePijOZpnPQ3Lnxbz-
"""

# instalacion automatica de las dependencias necesarias
!pip install -q torch datasets matplotlib nltk pandas

import re
import math
import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from collections import Counter

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from datasets import load_dataset
import nltk
from nltk.translate.bleu_score import corpus_bleu

nltk.download('punkt', quiet=True)

# configuracion global y definicion de hiperparametros
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"dispositivo de procesamiento: {device}")

PAD, UNK, SOS, EOS = 0, 1, 2, 3
SPECIAL_TOKENS =['<PAD>', '<UNK>', '<SOS>', '<EOS>']

EMBED_DIM  = 256
NUM_HEADS  = 8
NUM_LAYERS = 3
FFN_DIM    = 512
MAX_LEN    = 50
BATCH_SIZE = 64
EPOCHS     = 30
TRAIN_SIZE = 8000

# carga y filtrado del conjunto de datos opus100
def cargar_dataset():
    print("cargando el conjunto de datos opus100 ingles-espanol desde huggingface...")
    raw_dataset = load_dataset("opus100", "en-es", split="train")

    pares = []
    for item in raw_dataset:
        src = item['translation']['es'].strip()
        tgt = item['translation']['en'].strip()
        if 3 <= len(src.split()) <= 25 and 3 <= len(tgt.split()) <= 25:
            pares.append((src, tgt))

    random.seed(42)
    random.shuffle(pares)
    pares = pares[:9000]

    pares_train = pares[:TRAIN_SIZE]
    pares_val   = pares[TRAIN_SIZE:]
    return pares_train, pares_val

# preprocesamiento y construccion de vocabularios
def tokenizar(texto):
    texto = texto.lower()
    texto = re.sub(r"([.,!?;:])", r" \1 ", texto)
    texto = re.sub(r"\s+", " ", texto).strip()
    return texto.split()

def construir_vocab(pares, idx_idioma, min_freq=2):
    conteo = Counter()
    for par in pares:
        conteo.update(tokenizar(par[idx_idioma]))
    vocab = {tok: i for i, tok in enumerate(SPECIAL_TOKENS)}
    for palabra, freq in conteo.items():
        if freq >= min_freq:
            vocab[palabra] = len(vocab)
    return vocab

def preparar_vocabularios(pares_train):
    vocab_es = construir_vocab(pares_train, idx_idioma=0)
    vocab_en = construir_vocab(pares_train, idx_idioma=1)
    idx2es   = {v: k for k, v in vocab_es.items()}
    idx2en   = {v: k for k, v in vocab_en.items()}
    return vocab_es, vocab_en, idx2es, idx2en

def texto_a_tensor(texto, vocab):
    tokens  = tokenizar(texto)[:MAX_LEN]
    indices =[vocab.get(t, UNK) for t in tokens]
    return [SOS] + indices + [EOS]

class TatoebaDataset(Dataset):
    def __init__(self, pares, vocab_es, vocab_en):
        self.pares    = pares
        self.vocab_es = vocab_es
        self.vocab_en = vocab_en

    def __len__(self):
        return len(self.pares)

    def __getitem__(self, idx):
        src, tgt = self.pares[idx]
        src_tensor = torch.tensor(texto_a_tensor(src, self.vocab_es), dtype=torch.long)
        tgt_tensor = torch.tensor(texto_a_tensor(tgt, self.vocab_en), dtype=torch.long)
        return src_tensor, tgt_tensor

def collate_fn(batch):
    srcs, tgts = zip(*batch)
    srcs = nn.utils.rnn.pad_sequence(srcs, batch_first=True, padding_value=PAD)
    tgts = nn.utils.rnn.pad_sequence(tgts, batch_first=True, padding_value=PAD)
    return srcs, tgts

# arquitectura del transformador
class PositionalEncoding(nn.Module):
    def __init__(self, embed_dim, max_len=5000, dropout=0.1):
        super().__init__()
        self.dropout = nn.Dropout(dropout)
        pe  = torch.zeros(max_len, embed_dim)
        pos = torch.arange(0, max_len).unsqueeze(1).float()
        div = torch.exp(torch.arange(0, embed_dim, 2).float() * (-math.log(10000.0) / embed_dim))
        pe[:, 0::2] = torch.sin(pos * div)
        pe[:, 1::2] = torch.cos(pos * div)
        self.register_buffer('pe', pe.unsqueeze(0))

    def forward(self, x):
        x = x + self.pe[:, :x.size(1)]
        return self.dropout(x)

class TranslatorTransformer(nn.Module):
    def __init__(self, src_vocab_size, tgt_vocab_size, embed_dim, num_heads, num_layers, ffn_dim, dropout=0.1):
        super().__init__()
        self.src_embedding = nn.Embedding(src_vocab_size, embed_dim, padding_idx=PAD)
        self.tgt_embedding = nn.Embedding(tgt_vocab_size, embed_dim, padding_idx=PAD)
        self.pos_encoding  = PositionalEncoding(embed_dim, dropout=dropout)
        self.transformer = nn.Transformer(
            d_model=embed_dim, nhead=num_heads, num_encoder_layers=num_layers,
            num_decoder_layers=num_layers, dim_feedforward=ffn_dim, dropout=dropout, batch_first=True
        )
        self.fc_out = nn.Linear(embed_dim, tgt_vocab_size)

    def forward(self, src, tgt, src_key_padding_mask, tgt_key_padding_mask, tgt_mask):
        src_emb = self.pos_encoding(self.src_embedding(src))
        tgt_emb = self.pos_encoding(self.tgt_embedding(tgt))
        out = self.transformer(
            src_emb, tgt_emb, tgt_mask=tgt_mask, src_key_padding_mask=src_key_padding_mask,
            tgt_key_padding_mask=tgt_key_padding_mask, memory_key_padding_mask=src_key_padding_mask
        )
        return self.fc_out(out)

def crear_mascara_padding(secuencia):
    return (secuencia == PAD).to(device)

def crear_mascara_causal(size):
    return nn.Transformer.generate_square_subsequent_mask(size).to(device)

# funciones de entrenamiento y evaluacion
def entrenar_epoch(modelo, loader, criterio, optimizador, vocab_en):
    modelo.train()
    perdida_total = 0
    for src, tgt in loader:
        src, tgt = src.to(device), tgt.to(device)
        tgt_input  = tgt[:, :-1]
        tgt_output = tgt[:, 1:]
        src_pad_mask = crear_mascara_padding(src)
        tgt_pad_mask = crear_mascara_padding(tgt_input)
        tgt_mask     = crear_mascara_causal(tgt_input.size(1))

        optimizador.zero_grad()
        pred = modelo(src, tgt_input, src_pad_mask, tgt_pad_mask, tgt_mask)
        pred = pred.reshape(-1, len(vocab_en))
        tgt_output = tgt_output.reshape(-1)

        perdida = criterio(pred, tgt_output)
        perdida.backward()
        torch.nn.utils.clip_grad_norm_(modelo.parameters(), 1.0)
        optimizador.step()
        perdida_total += perdida.item()
    return perdida_total / len(loader)

def evaluar_epoch(modelo, loader, criterio, vocab_en):
    modelo.eval()
    perdida_total = 0
    with torch.no_grad():
        for src, tgt in loader:
            src, tgt = src.to(device), tgt.to(device)
            tgt_input  = tgt[:, :-1]
            tgt_output = tgt[:, 1:]
            src_pad_mask = crear_mascara_padding(src)
            tgt_pad_mask = crear_mascara_padding(tgt_input)
            tgt_mask     = crear_mascara_causal(tgt_input.size(1))

            pred = modelo(src, tgt_input, src_pad_mask, tgt_pad_mask, tgt_mask)
            pred = pred.reshape(-1, len(vocab_en))
            tgt_output = tgt_output.reshape(-1)
            perdida_total += criterio(pred, tgt_output).item()
    return perdida_total / len(loader)

def traducir(oracion_es, modelo, vocab_es, idx2en, max_len=50):
    modelo.eval()
    with torch.no_grad():
        src_indices = texto_a_tensor(oracion_es, vocab_es)
        src = torch.tensor(src_indices, dtype=torch.long).unsqueeze(0).to(device)
        src_pad_mask = crear_mascara_padding(src)
        src_emb = modelo.pos_encoding(modelo.src_embedding(src))
        memoria = modelo.transformer.encoder(src_emb, src_key_padding_mask=src_pad_mask)

        tgt_indices = [SOS]
        for _ in range(max_len):
            tgt = torch.tensor(tgt_indices, dtype=torch.long).unsqueeze(0).to(device)
            tgt_emb = modelo.pos_encoding(modelo.tgt_embedding(tgt))
            tgt_mask = crear_mascara_causal(tgt.size(1))
            salida = modelo.transformer.decoder(tgt_emb, memoria, tgt_mask=tgt_mask, memory_key_padding_mask=src_pad_mask)
            logits = modelo.fc_out(salida[:, -1, :])
            next_token = logits.argmax(dim=-1).item()
            tgt_indices.append(next_token)
            if next_token == EOS:
                break

        tokens =[idx2en.get(i, '<UNK>') for i in tgt_indices[1:] if i not in (SOS, EOS, PAD)]
        return ' '.join(tokens)

def calcular_bleu(modelo, pares_val, vocab_es, idx2en):
    referencias = []
    hipotesis =[]
    print("calculando metrica bleu sobre el conjunto de validacion...")
    for src, tgt in pares_val[:200]:
        traduccion = traducir(src, modelo, vocab_es, idx2en)
        referencias.append([tokenizar(tgt)])
        hipotesis.append(tokenizar(traduccion))
    score = corpus_bleu(referencias, hipotesis)
    print(f"puntuacion bleu obtenida: {score:.4f}")
    return score

# ejecucion principal
pares_train, pares_val = cargar_dataset()
vocab_es, vocab_en, idx2es, idx2en = preparar_vocabularios(pares_train)

train_dataset = TatoebaDataset(pares_train, vocab_es, vocab_en)
val_dataset   = TatoebaDataset(pares_val, vocab_es, vocab_en)
train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True, collate_fn=collate_fn)
val_loader = DataLoader(val_dataset, batch_size=BATCH_SIZE, shuffle=False, collate_fn=collate_fn)

modelo = TranslatorTransformer(len(vocab_es), len(vocab_en), EMBED_DIM, NUM_HEADS, NUM_LAYERS, FFN_DIM).to(device)
criterio = nn.CrossEntropyLoss(ignore_index=PAD)

# implementacion del programador de tasa de aprendizaje con calentamiento
optimizador = optim.Adam(modelo.parameters(), lr=0.0005, betas=(0.9, 0.98), eps=1e-9)
scheduler = optim.lr_scheduler.OneCycleLR(optimizador, max_lr=0.001, steps_per_epoch=len(train_loader), epochs=EPOCHS, pct_start=0.1)

historial = {'epoch': [], 'train_loss': [], 'val_loss':[]}

print("iniciando el entrenamiento del transformador...")
for epoch in range(1, EPOCHS + 1):
    train_loss = entrenar_epoch(modelo, train_loader, criterio, optimizador, vocab_en)
    val_loss = evaluar_epoch(modelo, val_loader, criterio, vocab_en)
    scheduler.step()
    historial['epoch'].append(epoch)
    historial['train_loss'].append(train_loss)
    historial['val_loss'].append(val_loss)
    print(f"epoca {epoch}/{EPOCHS} - perdida entrenamiento: {train_loss:.4f} - perdida validacion: {val_loss:.4f}")

# guardado de metricas y graficas
df_logs = pd.DataFrame(historial)
df_logs.to_csv('logs_entrenamiento.csv', index=False)

plt.figure(figsize=(10, 5))
plt.plot(historial['epoch'], historial['train_loss'], label='perdida entrenamiento')
plt.plot(historial['epoch'], historial['val_loss'], label='perdida validacion')
plt.xlabel('epocas')
plt.ylabel('entropia cruzada')
plt.title('curva de aprendizaje del transformador')
plt.legend()
plt.grid(True, alpha=0.3)
plt.savefig('curva_aprendizaje_traductor.png')

bleu_score = calcular_bleu(modelo, pares_val, vocab_es, idx2en)

checkpoint = {'modelo': modelo.state_dict(), 'vocab_es': vocab_es, 'idx2en': idx2en}
torch.save(checkpoint, 'modelo_traductor_mejorado.pt')
print("proceso finalizado exitosamente. archivos generados y listos para descarga.")

